export const APP_ROUTE_PATHS = {
  AUTH: {
    ROOT: "/auth",
    LOGIN: "/auth/login",
    SIGNUP: "/auth/signup",
    REGISTER: "/auth/register",
    SESSION_EXPIRED: "/auth/session-expired",
    ONBOARD_USER_PREFIX: "/auth/onboard-user",
    RESET_PASSWORD: "/auth/resetPassword",
    UPDATE_PASSWORD_PREFIX: "/auth/updatePassword/",
    PASSWORDLESS_LINK_REVOKED: "/auth/passwordless/link-revoked",
    PASSWORDLESS_REVOKE: "/auth/passwordless/revoke",
    PASSWORDLESS_VERIFY: "/auth/passwordless/verify",
  },
  ADMIN: {
    ROOT: "/admin",
  },
  DASHBOARD: {
    OVERVIEW: "/dashboard",
    TICKETS: "/dashboard/ticket-management",
    MANAGE_TICKET: "/dashboard/ticket-management/manage",
    CHAT: "/dashboard/chat",
    USERS: "/dashboard/users",
    PROPERTIES: "/dashboard/properties",
    TENANTS: "/dashboard/tenants",
    REPORTS: "/dashboard/reports",
    EXPORT_VERIFY: "/dashboard/exports/verify",
    WORKSPACES: "/dashboard/workspaces",
    SETTINGS: "/dashboard/settings",
    PAYMENTS: "/dashboard/payments",
    VOLUNTEERS: "/dashboard/volunteers",
    VOLUNTEER_TIMECARDS: "/dashboard/volunteers/timecards",
    RESERVATIONS: "/dashboard/reservations",
    TEAM: "/dashboard/team",
    ACCESS_CONTROL: "/dashboard/access-control",
  },
  ADMIN_DASHBOARD: {
    OVERVIEW: "/dashboard",
    TICKETS: "/dashboard/ticket-management",
    CHAT: "/dashboard/chat",
    USERS: "/dashboard/users",
    PROPERTIES: "/dashboard/properties",
    SETTINGS: "/dashboard/settings",
  },
  TECHNICIAN_DASHBOARD: {
    OVERVIEW: "/dashboard",
    TICKETS: "/dashboard/ticket-management",
    CHAT: "/dashboard/chat",
    SETTINGS: "/dashboard/settings",
  },
  PUBLIC: {
    REPORT_SHARE: "/report/share",
  },
} as const;
